[DCaaS] Implementing Direct Connect as a Service (#546)
[DCaaS] Implementing Direct Connect as a Service

What this PR does / why we need it

Implements support for Direct Connect as a Service (DCaaS) in the Golang SDK.
Introduces new structs, methods, and API calls for managing DCaaS resources.
Provides users with the ability to configure and manage connections, virtual gateways, virtual interfaces, and DC endpoint groups

Related Issue
SDK for opentelekomcloud/terraform-provider-opentelekomcloud#2215
Acceptance tests passed:
=== RUN   TestDirectConnectLifecycle
--- PASS: TestDirectConnectLifecycle (3.91s)
PASS

Process finished with the exit code 0

=== RUN   TestVirtualGatewayLifecycle
--- PASS: TestVirtualGatewayLifecycle (1.75s)
PASS

Process finished with the exit code 0

=== RUN   TestDirectConnectEndpointGroupLifecycle
--- PASS: TestDirectConnectEndpointGroupLifecycle (2.02s)
PASS

Process finished with the exit code 0

=== RUN   TestVirtualInterfaceLifecycle
    virtual_interface_test.go:32: Failure in virtual_interface_test.go, line 32: unexpected error "Resource not found: [POST https://dcaas.eu-de.otc.t-systems.com/v2.0/dcaas/virtual-interfaces], error message: {\"requestId\":\"49c10809b215e9fa039f27aa33fe3ea8\",\"error_msg\":\"DirectConnection b07d42dc-6137-4af3-a93b-853d879ae268 could not be found.\",\"error_code\":\"DC.1012\"}"
--- FAIL: TestVirtualInterfaceLifecycle (1.12s)

FAIL

Reviewed-by: Anton Sidelnikov
Reviewed-by: Artem Lifshits